language: python

sudo: false

python:
    - 3.6

cache: pip

virtualenv:
     system_site_packages: false

install:
    - pip install pipenv
    - pipenv install --system

before_script: cd site/

script:
- nikola build --no-continue --strict
